name: Linux Build

on:
  push:
    branches: 
        - master
        - feature/* 
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init --recursive --remote    
    - name: install alsa
      run: sudo apt-get update && sudo apt-get install -y libasound2 libasound2-dev
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      env:
        WM_DOWNLOAD_EXTERNALS: 1
        WM_LINUX_LINK_STATIC: 1
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    - name: test
      run: ./rehearse
      working-directory: build      
    - name: pack
      run: cmake --build . --config Release --target package
      working-directory: build
    - uses: actions/upload-artifact@v1
      with:
        name: werckmeister-linux-${{ github.sha }}
        path: build/werckmeister-0.1.53-Linux.sh
