name: Mac Build

on:
  push:
    branches: 
        - main
        - feature/* 
        - develop
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init --recursive --remote
    - name: install boost
      run: brew install boost
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      env:
        WM_DOWNLOAD_EXTERNALS: 0
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    - name: test
      run: ./rehearse
      working-directory: build 
    - name: pack
      run: cmake --build . --config Release --target package
      working-directory: build
    - uses: actions/upload-artifact@v1
      with:
        name: werckmeister-mac-${{ github.sha }}
        path: build/werckmeister-0.1.56-Darwin.sh
